### ISSUE TITLE
Shorten with ANSI codes?

### ISSUE THREAD

**Issue by MinchinWeb** [jonathaneunice/ansiwrap#3]
Is there a way to shorten a string, while maintaining the embedded ANSI codes? (so the resulting string is still colored, just shorter)

**Comment by jonathaneunice** [comment]
Does `shorten()` not work for you? It is designed to perserve ANSI codes as it shortens. It tests and works successfully for me.

```python
In [1]: from colors import *

In [2]: from ansiwrap import *

In [3]: s = red('this is good')

In [4]: shorten(s, 10)
Out[4]: '\x1b[31mthis [...]\x1b[0m'
```

If it is not correctly working for you, please submit a case in which it doesn't work. Happy to review error reports.

**Comment by MinchinWeb** [comment]
I got the colours to work. Turns out I was stripping the colour codes myself (oops!).

Is there a way use `shorten()` without collapsing the whitespace? (I release that the current behavour matches that of the standard library's textwrap module.)

**Comment by MinchinWeb** [comment]
Also, this breaks:

```
from ansiwrap import shorten

shorten('', 79)
```

**Comment by jonathaneunice** [comment]
A new [ansiwrap 0.8.3](https://pypi.python.org/pypi/ansiwrap/0.8.3) fixes the `shorten()` edge case breakage.

**Comment by jonathaneunice** [comment]
There is no way to use `shorten()` without collapsing whitespace. The [textwrap code](https://github.com/python/cpython/blob/188aedf8bb623d41302e10503268b0852ea91134/Lib/textwrap.py#L405-L405) does a `text.strip().split()` which will inherently collapse all whitespace, regardless of the `replace_whitespace` or `drop_whitespace` options.  It's arguable it should not work that way—but that's the way it currently works. `ansiwrap` just follows core `textwrap` on that decision. 

Would it be possible to create a non-whitespace-replacing version of shorten? Sure. But it's not trivial, because the core `TextWrapper` object, while it has a `max_lines` parameter, has no `max_characters` that it implicitly obeys. 

If you want just a string truncate that respects whitespace, you'd have to do that at a pretty low level. For example, a bare-bones function (without a fancy placeholder) might look something like this:

```python
import re
from ansiwrap.core import ansilen, ansi_terminate_lines
from ansiwrap.ansistate import ANSIState

FULLANSIRE = re.compile('(\x1b\\[(?:K|.*?m))')
    
def truncate(text, width):
    """
    Return the first width characters of text.
    Width is computed counting only non-ANSI
    sequences.
    """
    if ansilen(text) <= width:
        return text
    parts = FULLANSIRE.split(text)
    total = 0
    accum = []
    for part in parts:
        p_len = ansilen(part)
        if total + p_len <= width:
            # more room, add more
            total += p_len
            accum.append(part)
        else:
            # no more room - possibly truncate last part
            if FULLANSIRE.match(part):
                break
            else:
                remaining = width - total
                partial = part[:remaining]
                accum.append(partial)
                break
    # combine to feed through line-oriented terminator function
    combined = ''.join(accum)
    term = ansi_terminate_lines([combined])
    truncated = '\n'.join(term)
    return truncated
```

If you really wanted to flesh out this idea, it'd probably be best to add a `placeholder` option. And of course you'd need tests.

**Comment by MinchinWeb** [comment]
...hmmm. I'll have to see whether it bothers me enough to make it work. Should this function go in this library, or in your [textwrap3](https://github.com/jonathaneunice/textwrap3) library?

**Comment by jonathaneunice** [comment]
Probably start in `ansiwrap`. 

There may be space to extend`textwrap3.shorten()`, or even suggest changes to the core `textwrap.shorten()` to accommodate your "truncate, but don't munge whitespace" requirement. But ANSI interpretation adds a lot of complexities. Based on currently available abstractions, a better `shorten()` or `truncate()` is probably going to need special handling in `ansiwrap` anyway. So might as well start there.
